service: ServerlessNotes
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  createUser:
    handler: functions/user/createUser/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: functions/user/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST
  getNotes:
    handler: functions/notes/get/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: GET
  createNotes:
    handler: functions/notes/create/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: POST
  updateNotes:
    handler: functions/notes/update/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: PUT
  deleteNotes:
    handler: functions/notes/delete/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: DELETE

resources:
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST